// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPdWt6rwLRBW_0D9UAW2UyH6VrQEhm_Ck',
    appId: '1:373979149916:ios:88339bc853c116240f5899',
    messagingSenderId: '373979149916',
    projectId: 'chat-app-b5eb3',
    storageBucket: 'chat-app-b5eb3.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPdWt6rwLRBW_0D9UAW2UyH6VrQEhm_Ck',
    appId: '1:373979149916:ios:88339bc853c116240f5899',
    messagingSenderId: '373979149916',
    projectId: 'chat-app-b5eb3',
    storageBucket: 'chat-app-b5eb3.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlR7ho1p71Da20Ne3QUu_I3oTX9-VNpNU',
    appId: '1:373979149916:web:e9346cf7123efebc0f5899',
    messagingSenderId: '373979149916',
    projectId: 'chat-app-b5eb3',
    authDomain: 'chat-app-b5eb3.firebaseapp.com',
    storageBucket: 'chat-app-b5eb3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADwq1Eka4oAAKPZqOSjl9UFz6jM1bQk6s',
    appId: '1:373979149916:android:b3281215d22efc280f5899',
    messagingSenderId: '373979149916',
    projectId: 'chat-app-b5eb3',
    storageBucket: 'chat-app-b5eb3.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlR7ho1p71Da20Ne3QUu_I3oTX9-VNpNU',
    appId: '1:373979149916:web:0457e6e031d4865c0f5899',
    messagingSenderId: '373979149916',
    projectId: 'chat-app-b5eb3',
    authDomain: 'chat-app-b5eb3.firebaseapp.com',
    storageBucket: 'chat-app-b5eb3.firebasestorage.app',
  );

}